export const FETCH_BOTTLES = 'FETCH_BOTTLES'
export const FETCH_BOTTLE = 'FETCH_BOTTLE'
export const ADD_BOTTLE = 'ADD_BOTTLE'
export const UPDATE_BOTTLE = 'UPDATE_BOTTLE'
export const REMOVE_BOTTLE = 'REMOVE_BOTTLE'

export const SET_SERVER = 'SET_SERVER'
export const UNSET_SERVER = 'UNSET_SERVER'

export const STORE_MEASUREMENT = 'STORE_MEASUREMENT'
export const FETCH_MEASUREMENTS = 'FETCH_MEASUREMENTS'
